languageCode = "en-us"
title = "lesson-7-firebase-multisite-hosting"
description = "Multisite Firebase Hosting Example"
metadataformat = "yaml"
canonifyurls = true
disqusShortname = "ajonp"
enableGitInfo = "true"
pygmentsUseClasses = "true"
pygmentsCodeFences = "true"
ignoreFiles = [ "README.md" ]
[author]
  name = "ajonp"
  homepage = "https://ajonp.com"

[taxonomies]
  authors = "authors"
  tag = "tags"
  category = "categories"
  languages = "languages"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  toc = "true"
  RSSLink = "/index.xml"
  author = "ajonp"
  github = "ajonpllc"
  twitter = "ajonpcom"
  youtube = "UCnKZ8gEb78zXKMi1ns-IQ2g" #channelname
  slack = "ajonp-com"
  email = "developer@ajonp.com"
  images = ["https://res.cloudinary.com/ajonp/image/upload/w_500/v1543267002/ajonp-ajonp-com/youtube_banner.png"]
  fb_app_id = "1789405951311946"
  addThis = "ra-5c0988f0bf0a52da"

  # Search Only
  [params.algolia]
    appId = "DKKVXPOQMA"
    apiKey = "0a9ae037390dffeef403ccb8f2f9acbe"
    indexName = "prod_ajonp"
  # Allows for homepage based items
  [params.home]
    image = "https://res.cloudinary.com/ajonp/image/upload/v1544021089/ajonp-ajonp-com/Logos/ajonp/welcom_card.png"
    title = "Welcome to AJonP"
    subtitle = "Here you will find lessons and videos to coach you on your programming journey."
    socialTitle = "Visit AJ round the web!"
    showGithub = true
    showTwitter = true
    showYoutube = true
    showSlack = true

[[menu.main]]
    name = "Home"
    pre = "home"
    weight = -1
    url = "/"
[[menu.main]]
    name = "Lessons"
    pre = "school"
    weight = 100
    url = "/lessons/"
[[menu.main]]
    name = "Blog"
    pre = "book"
    weight = 200
    url = "/blog/"
[[menu.main]]
    name = "Categories"
    pre = "apps"
    weight = 300
    url = "/categories/"
[[menu.main]]
    name = "External References"
    pre = "link"
    weight = 400
    url = "/references/"
# [[menu.main]]
#     name = "Tags"
#     pre = "pricetag"
#     weight = 500
#     url = "/tags/"
# [[menu.main]]
#     name = "Coding Languages"
#     pre = "code"
#     weight = 600
#     url = "/languages/"
